export const communityQustionDummy = {
  result: {
    tags: [
      '오류',
      '질문',
      '파이썬',
      'JPA',
      '에러',
      'jpa',
      'react',
      'spring',
      '강의자료',
      'vue',
      '스프링',
      'python',
      'java',
      'error',
      'css',
      'html',
      'django',
      'docker',
      '리액트',
      'javascript',
    ],
    articles: [
      {
        id: 1,
        title: 'blackenergy2 샘플 다운로드',
        description:
          'https://github.com/volatilityfoundation/volatility/wiki/Memory-Samples 에서의 blackenergy 다운로드 주소가 http...',
        tags: [],
        name: 'Img8811',
        createdAt: '1분 전',
        courseTitle: '악성코드 분석을 위한 메모리 포렌식 (memory forensic)',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 2,
        title: 'M1 키클록 설치 ',
        description:
          'tar 파일로 kc.bat 을 실행했으나 되지 않는데도커 이용해서 키클록 다운받아야 합니까?',
        tags: [],
        name: 'home',
        createdAt: '3분 전',
        courseTitle:
          '스프링 시큐리티 OAuth2 - Spring Boot 기반으로 개발하는 Spring Security OAuth2',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 3,
        title: '인텔리제이 무료버전을 사용해서 그런데',
        description:
          'period같은 객체를 member에 작성할 때 @Embeddable을 사용해야 오류가 안난다고 나와있는데 team같은 객체는 member에 작성할 때 many to one같은 어노테이션을  작성해서 오류가 안나는 건가요?',
        tags: [],
        name: '동휘김',
        createdAt: '15분 전',
        courseTitle: 'RDBMS Modeling 기초',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 4,
        title: 'error: readStudents Query error ',
        description:
          '- 학습 관련 질문을 남겨주세요. 상세히 작성하면 더 좋아요! - 먼저 유사한 질문이 있었는지 검색해보세요. - 서로 예의를 지키며 존중하는 문화를 만들어가요. - 잠깐! 인프런 ...',
        tags: [],
        name: '신영현',
        createdAt: '35분 전',
        courseTitle:
          '비전공자를 위한 풀스택 맛집지도 만들기 프로젝트!: Front, Back-end 그리고 배포까지',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 5,
        title: '별이 안보여요. ',
        description:
          '분명 동일하게 코드를 작성했는대, 별이 보이지가 않아요. 풀 스크린으로 하는 것까진 정상적으로 됐는대, 별이 나오도록 코드 작성하는 부분부터는 별은 안나오고 그냥 흰 바탕...',
        tags: [],
        name: '임재',
        createdAt: '43분 전',
        courseTitle: '홍정모의 게임 만들기 연습 문제 패키지',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 6,
        title: 'static inner class 사용 이유 ',
        description:
          '안녕하세요 강사님KakaoUserInfoResponseDto 를 작성하실 때KakaoAccount를 스태틱 이너 클래스로 만드신 이유가 뭔지 알 수 있을까요? 클래스를 새로 생성하...',
        tags: ['Spring', 'SpringBoot'],
        name: '김진욱',
        createdAt: '59분 전',
        courseTitle:
          '생산성을 향상시키는 스프링부트 기반의 API 템플릿 프로젝트 구현',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 7,
        title: '6분 47초에 왜 업데이트 쿼리가 2번 나가는지 궁금합니다! ',
        description:
          '값이 변경되는건 1개인데 쿼리는 왜 2개나가는지 이해가 잘 되지않습니다.',
        tags: ['JPA', 'JAVA'],
        name: 'lsn5963',
        createdAt: '1시간 전',
        courseTitle: '자바 ORM 표준 JPA 프로그래밍 - 기본편',
        commentCount: 3,
        likeCount: 1,
      },
      {
        id: 8,
        title: '33%에서 "틀렸습니다"가 뜰 경우',
        description:
          'const int INT_MAX = 987654322 // 짝수"짝 + 홀 == 홀"을 응용하는 문제여서 끝자리를 짝수로 처리해줘야 하네요.혹시 같은 문제를 겪으신 분들에게 도움되...',
        tags: ['JPA', 'Spring'],
        name: 'Jeong Somang',
        createdAt: '1시간 전',
        courseTitle: '10주완성 C++ 코딩테스트 | 알고리즘 IT취업',
        commentCount: 2,
        likeCount: 1,
      },
      {
        id: 9,
        title: 'spread oparator ...가 deep copy 맞을까요?',
        description: 'spread oparator ... 가 deep copy 맞을까요?',
        tags: [],
        name: 'JH Lee',
        createdAt: '1시간 전',
        courseTitle: '따라하며 배우는 리액트 A-Z',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 10,
        title:
          'Choose the best way to book Southwest Airlines Booking in Low Cost? ',
        description:
          'Southwest Airlines Booking Festive Season. The 2022 low fare search of this airline is a planning to...',
        tags: [],
        name: 'jimmyarthur07',
        createdAt: '1시간 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 11,
        title: '사용하시는 프로그램 ',
        description:
          '강사님 수업 잘듣고있습니다.감사합니다. 다름이아니라 실습하면서 강의를 들으려고하는데실습프로그램을 알수있을까요?',
        tags: [],
        name: '동휘김',
        createdAt: '1시간 전',
        courseTitle: 'RDBMS Modeling 기초',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 12,
        title: '인텔리제이 무료버전을 사용해서 그런데 ',
        description:
          'period같은 객체를 member에 작성할 때 @Embeddable을 사용해야 오류가 안난다고 나와있는데team같은 객체는 member에 작성할 때 many to one같은 어노...',
        tags: [],
        name: 'lsn5963',
        createdAt: '1시간 전',
        courseTitle: '자바 ORM 표준 JPA 프로그래밍 - 기본편',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 13,
        title: 'data-alt 와 id 간의 관계 ',
        description:
          '안녕하세요!질문드립니다ㅠㅠ제가 이해를 못하는건지, 설명을 놓친건지 해서요.data-alt와 id를 attr로 엮을 때,앞에 #을 붙이면 id의 tab1이 되는거라는 설명이 이해가 ...',
        tags: [],
        name: 'chohyein94',
        createdAt: '2시간 전',
        courseTitle: 'HTML+CSS+JS 포트폴리오 실전 퍼블리싱(시즌1)',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 14,
        title: 'Repository test 관련해 질문이 있습니다. ',
        description:
          '안녕하세요! 강사님 덕분에 플러터 공부를 재미있게 하고 있는 수강생입니다. 다름이 아니라 클린 아키텍쳐를 이용하여 개인 프로젝트를 만들고 있는데 repository 테스트 코드를 ...',
        tags: [],
        name: 'dongwookim.dev',
        createdAt: '2시간 전',
        courseTitle: 'Flutter 실전 앱 개발 - 미국 주식 앱 (with 클린 아키텍처)',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 15,
        title: 'sendQueue 관련 질문입니다. ',
        description:
          '강의를 들으며 1send + sendQueue를 사용하는 경우의 장점은 1.더 많은 클라이언트를 받을 수 있다. 2.TCP 헤더가 적게 붙어 네트워크상 이점이 있다. 이렇게 생각했...',
        tags: [],
        name: '박성환',
        createdAt: '2시간 전',
        courseTitle:
          '[C++과 언리얼로 만드는 MMORPG 게임 개발 시리즈] Part4: 게임 서버',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 16,
        title: 'raccoon 정확도 ',
        description: 'raccoon 학습 때 정확도 구하는 방법을 알고 싶습니다.',
        tags: [],
        name: 'lusate',
        createdAt: '2시간 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 17,
        title: '웹드라이버가 m1에서 작동하지 않는것 같습니다.. ',
        description:
          '크롬 드라이버 자동 업데이트 부분에서부터 막히네요ㅜㅜ 이렇게 현재 m1에서는 웹드라이버가 정상적으로 작동하지 않고 있습니다ㅜㅜ 구글링해보니 얼마 안된 이슈인듯하네요ㅜㅜ',
        tags: [],
        name: 'sunny',
        createdAt: '2시간 전',
        courseTitle: '이것이 진짜 크롤링이다 - 실전편',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 18,
        title: '[05-1] 아래와 같이 return 함수에서만 괄호로 나옵니다. ',
        description:
          '안녕하세요?강의를 듣던 중에 제가 코딩한 것이 예상과 달라서 질문드립니다.같은 내용을 코딩하였는데 왜 아래는 괄호 안에 문구가 나오고, 위는 괄호 없이 문구가 나오나요??',
        tags: ['05-1', 'return'],
        name: '임금펭귄',
        createdAt: '2시간 전',
        courseTitle: '프로그래밍 시작하기 : 파이썬 입문 (Inflearn Original)',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 19,
        title: '세션과 스프링 시큐리티 ',
        description:
          '혹시 스프링 시큐리티를 쓰게 되면 이런식으로 request.getSession() 할 필요가 없나요?',
        tags: [],
        name: 'alrnr3521',
        createdAt: '2시간 전',
        courseTitle: '스프링 MVC 2편 - 백엔드 웹 개발 활용 기술',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 20,
        title:
          'repository 작성 시 , spring-data-jpa 의 jpaRepository 와 persistence manager 객체 주입의 선택 기준 ',
        description:
          '질문 : 실제 작업을 할때, 어떤 경우에 spring-data-jpa의 jpa repository 를 쓰고, 어떤 경우에 EntityManager 를 써야 할까요 ? 안녕하세요. ...',
        tags: ['jpa', 'spring-data-jpa', 'java', 'spring'],
        name: 'dankim',
        createdAt: '3시간 전',
        courseTitle: '실전! 스프링 부트와 JPA 활용1 - 웹 애플리케이션 개발',
        commentCount: 1,
        likeCount: 0,
      },
    ],
  },
}
