export const communityStudiesDummy = {
  result: {
    tags: [
      'react',
      'React',
      '파이썬',
      'java',
      '포트폴리오',
      '사이드프로젝트',
      '디자이너',
      'spring',
      '스터디',
      '프론트엔드',
      '알고리즘',
      '백엔드',
      '모각코',
      '자바스크립트',
      'javascript',
      '자바',
      '프로젝트',
      '코딩테스트',
      '스프링',
    ],
    articles: [
      {
        id: 1,
        recruited: true,
        title: '백엔드 스터디 ',
        description:
          '안녕하세요.백엔드 개발을 하고있는 현직자끼리 진행하는 스터디를 개설하고자 합니다 !자세한 설명은 아래의 링크에 적어놓았으니 참고 부탁드리겠습니다.감사합니다. [개발 스터디...',
        tags: [],
        name: '코드계의돌돔',
        createdAt: '1시간 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 2,
        recruited: true,
        title:
          '식글북적 독서모임 (서울) 함께 하실 분들을 모집합니다 (~10/20 23:59 신청마감) ',
        description:
          '안녕하세요, 지식을 흡수하는 독서법취삶선택 - 진짜 사명 찾기저자 라이프레이서입니다. 한 달간 이상적인 나를 만드는 독서모임 식글북적을 소개 드리고자 글을 쓰게 되었습...',
        tags: [
          '식글북적',
          '독서모임',
          '스터디',
          '자기계발',
          '인간관계',
          '심리학',
          '경제',
          '사업가',
          '개발자',
        ],
        name: '라이프레이서',
        createdAt: '1시간 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 3,
        recruited: true,
        title: '[서울] 주 2회 오프라인 공부하실 여자 개발자 모집해요! ',
        description:
          '안녕하세요 저는 30대 중반 여자, 3년차 자바 개발자구요같이 퇴근 후에 만나서 공부하실 여자 개발자분들 구해요저는 해외 이직을 목표로 삼고 있어서 저와 목표가 비슷한 분이었으면 ...',
        tags: ['해외취업', '백엔드', '영어', '스터디'],
        name: 'L HW',
        createdAt: '1시간 전',
        courseTitle: '',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 4,
        recruited: false,
        title: '앱개발 경험 쌓고 싶은 백엔드 개발자 모집 ',
        description:
          '앱 배포, 출시 경험 쌓아보실 백엔드 1명 구합니다.사이드 프로젝트로 팀원들을 모아 현재 진행 중입니다.12월이 출시 예정이고 현재 팀 작업은 디자인 40% 진행중입니다.개발팀은 ...',
        tags: [],
        name: '180621',
        createdAt: '4시간 전',
        courseTitle: '',
        commentCount: 4,
        likeCount: 2,
      },

      {
        id: 5,
        recruited: true,
        title:
          'IT직군 포트폴리오 + 블로그 플랫폼 사이트 프로젝트 팀원 구합니다. ',
        description:
          'https://productive-ornament-cad.notion.site/ff54d02eadd346b488c5e761414bf87f',
        tags: [],
        name: 'nhy8001',
        createdAt: '5시간 전',
        courseTitle: '',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 6,
        recruited: true,
        title: '[사이드 프로젝트] 현업자들과 함께하는 실무 기반 프로젝트 ',
        description: '크루 모집 공고 보러 가기',
        tags: [
          '기획',
          '디자이너',
          'swift',
          'android',
          'kotlin',
          'ios',
          'reactnative',
          'flutter',
          'mobile',
          'app',
        ],
        name: '개발쥬아',
        createdAt: '5시간 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 1,
      },
      {
        id: 7,
        recruited: false,
        title: '[ios] 개발 스터디 모집 ',
        description:
          '안녕하세요 스위프트를 활용한 ios 개발 스터디를 꾸려 볼까 합니다.진행 : 온라인요일 : 화요일주제 : 스위프트 문법 및 인터페이스빌더 사용방법, 오토레이아웃 이해시간 : 저녁 ...',
        tags: [],
        name: '김용연',
        createdAt: '6시간 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 8,
        recruited: false,
        title: '알고리즘 스터디 / 초급 / 백준 단계별풀이 ',
        description:
          '안녕하세요 ,주 2회 저녁 8시에 진행 중인 알고리즘 스터디입니다. 현재 인원은 2명입니다.백준 단계별 문제풀이 3개는 각자 해서, 게더타운에서 만나 가볍게 풀이를 공유한 후,프로...',
        tags: [],
        name: 'leese',
        createdAt: '21시간 전',
        courseTitle: '',
        commentCount: 2,
        likeCount: 1,
      },
      {
        id: 9,
        recruited: true,
        title: '온라인 모각코 인원 모집합니다! ',
        description:
          '안녕하세요, 같이 화면 공유하면서 모각코 진행하실 분을 모집합니다. 😊👤 대상 : 프론트엔드 개발자 취업이 목표이신 분💬 내용 : 각자 모여서 코딩 관련 스...',
        tags: [],
        name: 'it Do',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 10,
        recruited: true,
        title: '[프로젝트 팀원 모집] 프론트엔드 개발자를 모집합니다! ',
        description:
          '여행 기록 앱 서비스를 같이 만들어갈 프론트엔드 개발자를 모집합니다!아직 런칭 이전의 서비스이고 사이드 프로젝트 형태입니다. 함께 의미있는 프로젝트 경험을 하고 싶으신 프론트 개발...',
        tags: [],
        name: '이창주',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 11,
        recruited: true,
        title: '다이렉트 공부 스터디 모집합니다! ',
        description:
          '스터디 모집글을 아래 양식을 참고해 작성해주세요.마크다운, 단축키를 이용해서 편리하게 글을 작성할 수 있어요.꼼꼼히 작성하면 멋진 스터디 팀원을 만나실 수 있을거예요.[개발 스터디...',
        tags: [],
        name: 'k415129',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 12,
        recruited: true,
        title: '[프로젝트 팀원 모집] 백엔드 개발자를 모집합니다! ',
        description:
          '개발중입니다... 팀의 백엔드 개발자 모집!TEAM - 개발중입니다...제대로된 개발을 하고 싶으시다고요? 그런 당신을 위해 준비했습니다! 개발중입니다 팀!<!!중요!! 모집...',
        tags: ['Spring', 'Java', 'devops'],
        name: 'Roharui',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 13,
        recruited: false,
        title: '온라인 자체 교육 수강생 모집(100% 무료) ',
        description:
          'Python, Django, Git, AI 무료 실시간 온라인 강의 수강생을 모집합니다.  0. 강사 소개 :✔️ 개발하는 것이 재밌는 강사 전다운입니다.✔️ G...',
        tags: [
          '온라인교육',
          '무료교육',
          '실시간온라인',
          'python',
          'django',
          'git',
          'tensorflow',
          'pytorch',
          'ai',
        ],
        name: 'updowney',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 1,
      },
      {
        id: 14,
        recruited: true,
        title: '책읽기 스터디를 진행해보려고 합니다. ',
        description:
          '스터디 모집글을 아래 양식을 참고해 작성해주세요.마크다운, 단축키를 이용해서 편리하게 글을 작성할 수 있어요.꼼꼼히 작성하면 멋진 스터디 팀원을 만나실 수 있을거예요.[개발 스터디...',
        tags: [],
        name: 'javeedeveloper21',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 15,
        recruited: true,
        title: '자바 백엔드 스터디 모집합니다. ',
        description:
          '개발 공부 스터디 모집합니다.현재 저는 모 물류 대기업에 개발 및 유지보수 파트에서 웹개발 및 서버개발 프로그래머로 일하고 있습니다.현재 6개월차 신입이라 아직은 많이 부족하고 배...',
        tags: ['재직자', '이직준비', '스프링부트', 'mq', '프론트엔드', '자바'],
        name: 'Nell',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 8,
        likeCount: 1,
      },
      {
        id: 16,
        recruited: true,
        title: '코테 스터디 모집합니다! ',
        description:
          '스터디 모집글을 아래 양식을 참고해 작성해주세요.마크다운, 단축키를 이용해서 편리하게 글을 작성할 수 있어요.꼼꼼히 작성하면 멋진 스터디 팀원을 만나실 수 있을거예요.[개발 스터디...',
        tags: [],
        name: '제이비비',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 17,
        recruited: true,
        title: '운영체제 스터디 모집(모집중)',
        description:
          '안녕하세요!운영체제를 공부하려고 했지만 자꾸 미루게 돼서 스터디를 모집하게 됐습니다아래 내용 읽어보시고 스터디 할 생각이 있으시다면 PDF 문서(지원 방법 참고)와 함께 연락 주세...',
        tags: [],
        name: 'spencer9504',
        createdAt: '1일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 3,
      },
      {
        id: 18,
        recruited: true,
        title: 'CS 백엔드 스터디 모집합니다!',
        description:
          '스터디 모집글을 아래 양식을 참고해 작성해주세요.마크다운, 단축키를 이용해서 편리하게 글을 작성할 수 있어요.꼼꼼히 작성하면 멋진 스터디 팀원을 만나실 수 있을거예요.[개발 스터디...',
        tags: [],
        name: 'javeedeveloper21',
        createdAt: '2일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 1,
      },
      {
        id: 19,
        recruited: false,
        title: '온라인 FE 스터디 모집합니다!',
        description:
          '안녕하세요 ! 현재 , 컴퓨터공학과에서 대학교 3학년을 보내고 있는 Mapin이라고 합니다!저는 여러가지 분야의 개발을 접해보았고, 그 중에 Front-end가 제일 재밌고, 저한...',
        tags: [],
        name: 'Mapin',
        createdAt: '3일 전',
        courseTitle: '',
        commentCount: 1,
        likeCount: 2,
      },
      {
        id: 20,
        recruited: true,
        title: '석촌역 오프라인 모각코',
        description:
          '안녕하세요. 석촌역 근처 카페에서 주말마다 모각코 하실 분들을 모집중입니다.일요일 오전 10시 ~ 1시로 생각중입니다.안정되면 일요일 외에도 같이하고 싶을 때 자유롭게 열도록 할까...',
        tags: [],
        name: 'mias',
        createdAt: '3일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
    ],
  },
}
