export const coursesPageDummy = {
  result: {
    courses: [
      {
        imgUrl: 'courses-1.jpeg',
        lectureTitle: '비전공자를 위한 개발자 취업 올인원 가이드 [통합편]',
        badge: '25',
        badgeDay: '2',
        instructor: '한정수',
        starCnt: 5,
        reviewCnt: 126,
        del: '₩77,000',
        price: '₩57,750',
        students: '2400',
        isNew: false,
        isUpdate: false,
        isDiscount: true,
        description:
          '체육을 전공하고 29살에 개발 공부를 시작해서, 30살에 연봉 4천만원, 31살에 연봉 6천만원, 32살에 연봉 x천만원 이상 받는 탑티어 회사 개발자가 된 노하우를 모두 담았습니다!',
        level: '입문',
        category: '취업 · 이직, 교양 · 기타',
        skill: '면접, 포트폴리오',
      },
      {
        imgUrl: 'courses-2.jpeg',
        lectureTitle:
          '스프링 입문 - 코드로 배우는 스프링 부트, 웹 MVC, DB 접근 기술',
        instructor: '김영한',
        badge: '',
        badgeDay: '',
        starCnt: 5,
        reviewCnt: 4265,
        del: '',
        price: '무료',
        students: '53500',
        isNew: false,
        isUpdate: true,
        isDiscount: false,
        description:
          '스프링 입문자가 예제를 만들어가면서 스프링 웹 애플리케이션 개발 전반을 빠르게 학습할 수 있습니다.',
        level: '초급',
        category: '백엔드, 웹 개발',
        skill: 'Java, Spring, MVC',
      },
      {
        imgUrl: 'courses-3.jpeg',
        lectureTitle:
          '실제 이력서 사례로 알아보는 [합격하는 이력서] 작성 가이드',
        instructor: '워니',
        starCnt: 5,
        reviewCnt: 116,
        price: '₩49,500',
        students: '600',
        isNew: false,
        description:
          '최소한 이력서 때문에 취업이나 이직에 실패하는 일이 없기를 바라는 마음으로 준비한 강의입니다. 🙏 다양한 이력서 사례들과 실제 신입/경력 이력서 개선 과정을 통해 이력서 작성 방법을 배울 수 있습니다.',
        level: '입문',
        category: '취업 · 이직, 교양 · 기타',
        skill: '이력서, 면접',
      },
      {
        imgUrl: 'courses-4.jpeg',
        lectureTitle: '프로그래밍 시작하기:파이썬 입문(Inflearn Original)',
        badge: '25',
        instructor: '인프런',
        starCnt: 5,
        reviewCnt: 687,
        del: '₩55,000',
        price: '₩41,250',
        students: '13100',
        isNew: false,
        isUpdate: true,
        description:
          '이미 만명 이상이 학습하고 만족한 최고의 프로그래밍 입문 강의. 인프런이 비전공자 위치에서 직접 기획하고 준비한 프로그래밍 입문 강의로, 프로그래밍을 전혀 접해보지 못한 사람부터 실제 활용 가능한 프로그래밍 능력까지 갈 수 있도록 도와주는 강의입니다.',
        level: '입문',
        category: '프로그래밍 언어',
        skill: 'Python, 딥러닝',
      },
      {
        imgUrl: 'courses-5.jpeg',
        lectureTitle:
          '[C#과 유니티로 만드는 MMORPG 게임 개발 시리즈] Part1: C# 기초: 프로그래밍 입문',
        instructor: 'Rookiss',
        badge: '25',
        badgeDay: '2',
        starCnt: 5,
        reviewCnt: 50,
        del: '₩44,000',
        price: '₩33,000',
        students: '100',
        isNew: false,
        isUpdate: true,
        isDiscount: true,
        description:
          '기초 프로그래밍 지식이 없는 사람들을 위한 C# 프로그래밍 기초 강의입니다.문법 암기 위주의 수업이 아니라, 최대한 필요한 부분만을 요약해서 진행합니다.',
        level: '입문',
        category: '게임 개발, 프로그래밍 언어',
        skill: 'C#',
      },
      {
        imgUrl: 'courses-6.jpeg',
        lectureTitle: '인프콘 2022 다시보기',
        instructor: '인프런',
        badge: '',
        badgeDay: '',
        starCnt: 5,
        reviewCnt: 8,
        del: '',
        price: '무료',
        students: '11800',
        isNew: false,
        isUpdate: true,
        isDiscount: false,
        description:
          '인프런의 첫 오프라인 콘퍼런스, 인프콘 2022에서 진행된 오프닝 및 발표 세션을 영상으로 다시 보실 수 있습니다.',
        level: '입문',
        category: '교양 · 기타, 기타',
        skill: '',
      },
      {
        imgUrl: 'courses-7.jpeg',
        lectureTitle: '따라하면서 배우는 고박사의 유니티 기초',
        instructor: '고박사',
        starCnt: 5,
        reviewCnt: 85,
        price: '무료',
        students: '6500',
        isNew: false,
        description:
          '유니티로 게임을 개발하고 싶은 초보자를 대상으로 하며, 유니티 설치부터 2D/3D 게임 개발에 필요한 기초 지식까지 자세하게 설명합니다. (강의에 사용되는 모든 리소스는 영상 상단의 "수업자료" 버튼을 눌러 다운로드 가능합니다.)',
        level: '입문',
        category: '게임 프로그래밍, 게임 개발',
        skill: 'Unity',
      },
      {
        imgUrl: 'courses-8.jpeg',
        lectureTitle: '컴퓨터,웹,코딩,프로그래밍의 시작 - Web1',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 508,
        price: '무료',
        students: '12500',
        isNew: false,
        description:
          '일반인에게 프로그래밍을 알려주는 생활코딩의 이고잉님이 진행한 크라우드펀딩 강좌 Web 1 입니다. 웹의 근간이 되는 HTML 로 웹페이지를 직접 만들어 보며, 누구나 코딩을 접해볼 기회를 가질 수 있는 강의 입니다.',
        level: '입문',
        category: '웹 개발',
        skill: 'HTML/CSS',
      },
      {
        imgUrl: 'courses-9.jpeg',
        lectureTitle: '퍼블리셔 개인 포트폴리오 홈페이지 제작 완벽 가이드(PDF)',
        badge: '20',
        badgeDay: '',
        instructor: '코딩웍스(Coding Works)',
        starCnt: 5,
        reviewCnt: 10,
        del: '₩38,500',
        price: '₩30,800',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        description:
          '취업을 위해 면접을 자주 봐야 합니다. 면접을 자주 보기 위해서는 괜찮은 퍼블리셔 개인 포트폴리오 홈페이지가 반드시 있어야 합니다. 코딩웍스가 심혈을 기울여 만든 괜찮은 개인 포트폴리오 홈페이지 제작 가이드 교재(PDF)입니다.해당 교재는 인터넷에서 구글링 해서 구할 수 있는 내용이 아닙니다. 코딩웍스가 수년간 현장에서 300여 명의 학생에게 퍼블리싱 이론, 실전, 개인 포트폴리오 홈페이지 제작 강의하고 학생들이 빨리 원하는 회사에 취업할 수 있도록 개인 포트폴리오 홈페이지 제작 방법을 상세하게 담은 세상에 하나뿐인 퍼블리셔 취업 개인 포트폴리오 홈페이지 제작 가이드(PDF) 입니다.',
        level: '초급',
        category: '웹 퍼블리싱, 취업 · 이직',
        skill: '포트폴리오, 웹 디자인, HTML/CSS',
      },
      {
        imgUrl: 'courses-10.jpeg',
        lectureTitle: '모두의 깃 & 깃허브',
        badge: '30',
        badgeDay: '',
        instructor: '강민철',
        starCnt: 5,
        reviewCnt: 3,
        del: '₩24,200',
        price: '₩16,940',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        description:
          '길벗출판사 [모두의 깃&깃허브] 서적의 강의입니다. 깃과 깃허브를 이용한 버전관리의 핵심만을 모았습니다. 개발자의 필수 교양이라 할 수 있는 깃을 명령어 없이, 명령어로 다루는 방법과 깃허브를 능수능란하게 다루는 방법을 배웁니다.',
        level: '입문',
        category: '개발도구',
        skill: 'Github, Git',
      },
      {
        imgUrl: 'courses-11.jpeg',
        lectureTitle: "고객의 친구가 되기 위한 	'UX Writing'",
        badge: '24',
        badgeDay: '',
        instructor: '켈리폴리',
        starCnt: 5,
        reviewCnt: 6,
        del: '₩44,000',
        price: '₩30,800',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        description:
          'UX Writing이 도대체 무엇이고, 왜 중요한지 궁금하신가요? 직접 잘 나가는 앱들의 사례를 보면서 알 수 있을 거예요.',
        level: '입문',
        category: 'UX/UI, 기획 · 전략 · PM',
        skill: '카피라이팅, 서비스 기획',
      },
      {
        imgUrl: 'courses-12.jpeg',
        lectureTitle: '30분 요약강좌 시즌5 : 알작딱깔센 flex & grid',
        instructor: '제주코딩베이스캠프',
        starCnt: 5,
        reviewCnt: 7,
        price: '무료',
        students: '300',
        isNew: true,
        description:
          '알아서! 잘! 딱! 깔끔하고! 센스있게! 정리하는 flex & grid 책의 무료 강의입니다. 오픈소스 링크, 해당 책과 Notion 링크도 무료로 이용하실 수 있습니다. 비영리 프로젝트로 교재 활용도 허락 없이 가능합니다.',
        level: '초급',
        category: '웹 개발, 프론트엔드, 웹 퍼블리싱',
        skill: 'HTML/CSS, 반응형 웹, Flex',
      },
      {
        imgUrl: 'courses-13.jpeg',
        lectureTitle: '클라우드 서비스 AWS',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 174,
        price: '무료',
        students: '6100',
        isNew: false,
        description:
          '이 수업은 클라우드 서비스인 AWS(Amazon Web Services)의 기본적인 사용법과 파일의 저장공간을 제공하는 S3를 다루고 있는 수업입니다.  ',
        level: '초급',
        category: '데브옵스 · 인프라, 클라우드',
        skill: 'AWS',
      },

      {
        imgUrl: 'courses-14.jpeg',
        lectureTitle:
          '[백문이불여일타] 데이터 분석을 위한 SQL 실전표 (무료 미니 코스)',
        instructor: '데이터라인',
        starCnt: 5,
        reviewCnt: 32,
        price: '무료',
        students: '3100',
        isNew: false,
        description:
          '인프런 누적 수강생 10,000명 이상, 풍부한 온/오프라인 강의 경험을 가진 데이터리안의 SQL 실무 강의. SQL은 실무에서 어떻게 활용되고 있을까요? Microsoft의 Yammer 서비스의 실제 데이터를 이용하여 문제를 해결하는 데이터 분석가가 되어봅시다.',
        level: '중급이상',
        category: '데이터 분석, 기타',
        skill: 'SQL',
      },
      {
        imgUrl: 'courses-15.jpeg',
        lectureTitle: '비전공자를 위한 진짜 입문 올인원 개발 클래스',
        instructor: '그랩',
        badge: '25',
        badgeDay: '2',
        starCnt: 5,
        reviewCnt: 116,
        del: '₩143,000',
        price: '₩107,250',
        students: '2100',
        isNew: false,
        isUpdate: true,
        isDiscount: true,
        description:
          '왕초보도 할 수 있는 웹, 서버, 모바일 앱, 머신러닝까지 익히는 끝판왕 풀스택 강의!! 개발을 어디서부터 시작할지 막막했다면 이 강의를 강력 추천할게요. Javascript 하나로 진행합니다!',
        level: '입문',
        category: '풀스택, 웹 개발, 취업 · 이직, 프론트엔드',
        skill: 'JavaScript, React, Node.js',
      },

      {
        imgUrl: 'courses-16.jpeg',
        lectureTitle: 'Flutter 앱 개발 완성',
        instructor: 'DevStory',
        starCnt: 4,
        reviewCnt: 18,
        delPrice: '',
        price: '₩64,900',
        students: '200',
        isNew: false,
        description:
          'Android와 iOS 앱을 하나의 코드로 만들 수 있는 Flutter를 여러가지 앱을 만들며 배우는 수업입니다. 기초 문법과 이론부터 실습까지 비전공자 왕초보 분들도 따라오실 수 있도록 준비했습니다.',
        level: '입문',
        category: '모바일 앱 개발',
        skill: 'Flutter',
      },

      {
        imgUrl: 'courses-17.jpeg',
        lectureTitle: '블렌더 처음 시작부터 로우폴리 3D 애니메이션 까지',
        instructor: 'AZTechnology',
        badge: '25',
        badgeDay: '2',
        starCnt: 5,
        reviewCnt: 5,
        del: '₩49,500',
        price: '₩37,120',
        students: '100',
        isNew: false,
        isUpdate: false,
        isDiscount: true,
        description:
          '블렌더 완전 기초부터 로우폴리 3D 애니메이션 까지 만들 수 있는 강의',
        level: '입문',
        category: 'CAD · 3D 모델링, 디자인 툴, 게임 아트 · 그래픽',
        skill: 'Blender',
      },
      {
        imgUrl: 'courses-18.jpeg',
        lectureTitle: '생활코딩 - 자바스크립트 (JavaScript) 기본',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 372,
        price: '무료',
        students: '20300',
        isNew: false,
        description:
          '생활코딩의 자바스크립트 언어 기본 수업입니다. 기본 문법을 통한 자바스크립트 기본에 대해 배울 수 있습니다.',
        level: '입문',
        category: '프로그래밍 언어',
        skill: 'JavaScript',
      },
      {
        imgUrl: 'courses-19.jpeg',
        lectureTitle: 'JPA & Spring Data JPA 기초',
        instructor: '최범균',
        starCnt: 5,
        reviewCnt: 104,
        price: '무료',
        students: '500',
        isNew: true,
        description: 'JPA와 스프링 데이터 JPA의 기본 사용법을 알아봅니다.',
        level: '초급',
        category: '백엔드, 웹 개발',
        skill: 'Spring, JPA',
      },
      {
        imgUrl: 'courses-20.jpeg',
        lectureTitle: 'UI와 함께 배우는 Swift - 레벨 2',
        badge: '',
        badgeDay: '',
        instructor: '리이오',
        starCnt: 5,
        reviewCnt: 1,
        del: '',
        price: '무료',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: false,
        description:
          '터미널에서 문법을 배우고 있나요? 별 찍기를 하면서 문법을 공부하나요? 문법 공부, 다양한 예제로 재미있게 접근해요!',
        level: '입문',
        category: '모바일 앱 개발, 프로그래밍 언어',
        skill: 'Swift, SwiftUI',
      },
      {
        imgUrl: 'courses-21.jpeg',
        lectureTitle: '[입문자를 위한 UE5] Part2.언리얼 엔진 2D 게임 개발 입문',
        badge: '30',
        badgeDay: '',
        instructor: 'Rookiss',
        starCnt: 5,
        reviewCnt: 10,
        del: '₩55,000',
        price: '₩38,500',
        students: '100',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        description:
          '언리얼 엔진을 이용해 간단한 2D 게임을 만들어 보는 강의입니다. 블루프린트를 실전에 사용할 수 있는 능력을 배양하고 자연스럽게 언리얼 엔진 기초 사용법을 터득할 수 있습니다.',
        level: '초급',
        category: '게임 프로그래밍, 게임 개발',
        skill: 'Unreal Engine, UE Blueprint',
      },
      {
        imgUrl: 'courses-22.jpeg',
        lectureTitle: '계산기로 시작해보는 SwiftUI',
        badge: '',
        badgeDay: '',
        instructor: '리이오',
        starCnt: 4,
        reviewCnt: 11,
        del: '',
        price: '무료',
        students: '',
        isNew: false,
        isUpdate: false,
        isDiscount: false,
        description:
          '따라만 하는 수업이 아니라, 기초를 다지기 위한 앱을 만들어 봅니다. 우리가 만들고 싶은 것들을 만들기 위해 무엇이 필요한지 알아보는 시간입니다.',
        level: '초급',
        category: '모바일 앱 개발',
        skill: 'SwiftUI, Swift',
      },
      {
        imgUrl: 'courses-23.jpeg',
        lectureTitle: '엑셀 분석작업의 모든것',
        badge: '10',
        badgeDay: '',
        instructor: '은희쌤',
        starCnt: 5,
        reviewCnt: 2,
        del: '₩11,000',
        price: '₩9,900',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        description:
          '데이터 분석으로 피벗테이블 많이 사용하시죠? 그러나 엑셀은 피벗테이블 외에도 상황에 맞는 다양한 분석작업을 제공합니다. 이번 강좌에서  엑셀 분석작업을 10가지 방법으로 총 정리해드립니다(정렬, 부분합, 피벗테이블, 피벗챠트, 목표값찾기, 데이터표, 시나리오관리자, 통합, 고급필터, 조건부서식)',
        level: '초급',
        category: '오피스',
        skill: 'Excel, MS-Office',
      },
      {
        imgUrl: 'courses-24.jpeg',
        lectureTitle:
          '따라하며 배우는 노드, 리액트 시리즈 - 레딧 사이트 만들기(NextJS)',
        badge: '20',
        badgeDay: '',
        instructor: 'John Ahn',
        starCnt: 5,
        reviewCnt: 3,
        del: '₩44,000',
        price: '₩35,200',
        students: '300',
        isNew: false,
        isUpdate: true,
        isDiscount: true,
        description:
          '이 강의를 통해서 레딧 웹사이트를 처음부터 하나하나 만들어 보실 수 있습니다.',
        level: '초급',
        category: '클론코딩, Node.js, React',
        skill: '카피라이팅, 서비스 기획',
      },
    ],
  },
}
