export const communityChatsDummy = {
  result: {
    banner: {
      title: '이야기를 나눠요',
      description: '97만명의 커뮤니티!! 함께 토론해봐요.',
    },
    tags: [
      '테스트',
      '파이썬',
      '백엔드',
      '프론트엔드',
      '오타',
      '자바',
      '사이드프로젝트',
      'spring',
      '블록체인',
      '완강',
      '스프링',
      '프로젝트',
      'java',
      '경진대회',
      '코드',
      '스터디',
      '개발자',
      '인공지능',
      'JPA',
      'python',
    ],
    articles: [
      {
        id: 1,
        title: '선생님이 최고시네요 ',
        description:
          '제가 지금 웹쪽 다른 강의 듣고있는데요, 문득 생각나서 글씁니다. 제가 강의 이곳저곳 많이 봐왔구요, 유명하다, 잘가르친다 이런 분들 강의 많이 봤다고 생각합니다. java,c,파...',
        tags: [],
        name: 'kyj1',
        createdAt: '2시간 전',
        courseTitle:
          '[코드팩토리] [중급] Flutter 진짜 실전! 상태관리, 캐시관리, Code Generation, GoRouter, 인증로직 등 중수가 되기 위한 필수 스킬들!',
        commentCount: 1,
        likeCount: 1,
      },
      {
        id: 2,
        title: 'curl -O https://kubetm.github.io/yamls/k8s-install/Vagrantfile',
        description:
          'curl -O https://kubetm.github.io/yamls/k8s-install/VagrantfileVagrantfile 파일 다운로드 시, 아래와 같은 에러 발생 한다...',
        tags: [],
        name: '이정현',
        createdAt: '3시간 전',
        courseTitle: '대세는 쿠버네티스 [초급~중급]',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 3,
        title: '다음 강의 ',
        description:
          '안녕하세요 선생님.자동차 회사에서 근무중인 신입사원입니다. 올려주신 UDS진단통신과 CAN통신 강의 너무 유익하게 시청했습니다. 혹시 다음 강의 계획은 어떤 내용인지 알고 싶습니다...',
        tags: [],
        name: '아자아자화이팅',
        createdAt: '9시간 전',
        courseTitle: 'CAN 통신 - 자동차 신입이 알아야 할 모든 것',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 4,
        title: '강의가 너무 빨라요. ',
        description:
          '초반에는 자세히 설명해주는데후반에는 자비없는 속도로 타자를 치면서 동시에 설명도 하니까강의를 따라가는게 아니라 그냥 읽어주는것 같습니다.  ',
        tags: [],
        name: 'Hanul Lee',
        createdAt: '12시간 전',
        courseTitle: '초간단 자바 - 비전공자를 위한 자바 프로그래밍 입문',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 5,
        title: '출석체크:) ',
        description: '출첵합니다 감사합니다:)',

        tags: [],
        name: '봄봄',
        createdAt: '18시간 전',
        courseTitle: 'HTML+CSS+JS 포트폴리오 실전 퍼블리싱(시즌1)',
        commentCount: 0,
        likeCount: 1,
      },
      {
        id: 6,
        title: 'invalid parameter : redirect_uri 해결법 공유합니다. ',
        description:
          '위와 같이 설정 하면 로그인 화면이 나옵니다.출처https://stackoverflow.com/questions/45352880/keycloak-invalid-parameter-r...',
        name: 'home',
        createdAt: '1일 전',
        courseTitle:
          '스프링 시큐리티 OAuth2 - Spring Boot 기반으로 개발하는 Spring Security OAuth2',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 7,
        title: '강의와는 상관없지만.. ',
        description:
          '현재 프론트엔드 개발자로 4개월째 근무하고있는 쥬니어입니다.현재 참가하는 프로젝트에서 리덕스 + 리코일, 즉 상태관리툴을 두 개나 사용중인데요..리코일은 간단한 localStor...',
        name: 'Yoon Geon-ung',
        createdAt: '2일 전',
        courseTitle:
          '프론트엔드 개발환경의 이해와 실습 (webpack, babel, eslint..)',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 8,
        title: '수업 감사합니다:) ',
        description: '오늘도 좋은 수업 잘 들었습니다, 감사합니다:)',
        name: '봄봄',
        createdAt: '2일 전',
        courseTitle: 'HTML+CSS+JS 포트폴리오 실전 퍼블리싱(시즌1)',
        commentCount: 1,
        likeCount: 1,
      },
      {
        id: 9,
        title: '비전공자 자바/스프링 관련 조언 부탁드립니다 ',
        description:
          '비전공자로 늦은 나이(33살)에 다니던 회사를 그만두고 항해 99라는 부트캠프를 수료했지만, 노베이스 인 제게는 너무나 과정이 빨랐고, 열심히 한다고는 했는데, 그냥 속도 따라가기...',
        tags: [],
        name: 'sy k',
        courseTitle: '',
        createdAt: '2일 전',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 10,
        title: '잘봤습니다. ',
        description: '잘봤습니다. ',
        tags: [],
        name: '나효진',
        createdAt: '2일 전',
        courseTitle: '공공 데이터 (오픈 데이터) API 제대로 배우기 Part.1',
        commentCount: 0,
        likeCount: 0,
      },

      {
        id: 11,
        title: '[선착순 마감] 핀테크 특화 AI 엔지니어 취업연계 교육과정 ',
        description:
          '네카라쿠배 당토가 주목하는 산업?핀테크 특화 AI 엔지니어 취업까지 101일 완성번거로운 내일배움카드도 필요 없어요!서울 시민이라면 청년취업사관학교 등록금 전액무료! 최우...',
        tags: [],
        name: '학생~',
        createdAt: '4일 전',
        courseTitle: '',
        commentCount: 0,
        likeCount: 0,
      },
      {
        id: 12,
        title: '수업 감사합니다:) ',
        description: '오늘 수업도 덕분에 재밌게 잘 배웠습니다, 감사합니다:)',
        tags: [],
        name: '봄봄',
        createdAt: '4일 전',
        courseTitle: 'HTML+CSS+JS 포트폴리오 실전 퍼블리싱(시즌1)',
        commentCount: 0,
        likeCount: 1,
      },
      {
        id: 13,
        title: 'MVC 패턴 관련 ',
        description:
          '현재 JPA 실습을 하고 있는데 MVC패턴에 대하여 궁금하여 문의드립니다. 현재 프로젝트에서 View단인 resource 디렉토리를 제외한 나머지 부분이 모두 백엔드에 속하는건가...',
        tags: ['MVC', '백엔드', '프론트엔드'],
        name: '엄재정',
        createdAt: '4일 전',
        courseTitle: '실전! 스프링 부트와 JPA 활용1 - 웹 애플리케이션 개발',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 14,
        title: '블로그 저작권 문의 ',
        description:
          '안녕하세요강의를 들으면서 배운 내용들을 정리하여 강의 pdf 및 영상의 이미지와 중요코드들은 사용하지 않으며,출처표기하여 이론적인 내용들은 정리해서 복습할 겸 개인 블로그에 올려두...',
        tags: [],
        name: 'minju0426',
        createdAt: '5일 전',
        courseTitle: '냉동코더의 알기 쉬운 Modern Android Development 입문',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 15,
        title: 'Fluentd 구축 질문 ',
        description:
          '안녕하세요, 강사님!교육을 듣고 관련 업무를 하다 궁금한점이 있어 질의드립니다.현재 저는 쿠버네티스 환경에서 서비스 및 컨데이터의 로그 수집을 하려는데, 이를 위해 Flurnted...',
        tags: [],
        name: 'ajs9330',
        createdAt: '5일 전',
        courseTitle: '대세는 쿠버네티스 [초급~중급]',
        commentCount: 1,
        likeCount: 1,
      },
      {
        id: 16,
        title: '타자 소리가 너무 커요.. ',
        description:
          '키보드 치는 소리가 너무 커요. 마이크랑 같이 울려서 귀가 아프네여 ㅜ',
        tags: [],
        name: '신영현',
        createdAt: '6일 전',
        courseTitle:
          '비전공자를 위한 풀스택 맛집지도 만들기 프로젝트!: Front, Back-end 그리고 배포까지',
        commentCount: 2,
        likeCount: 0,
      },
      {
        id: 17,
        title: '오타 제보',
        description:
          '오타가 맞겠죠?자바 예외 이해.pdf 에서 2페이지에때문에다 라고 되어 있던데 때문이다라고 치려고 했지 않을까 생각되서요.',
        tags: [],
        name: 'padohy',
        createdAt: '6일 전',
        courseTitle: '스프링 DB 1편 - 데이터 접근 핵심 원리',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 18,
        title: '수업 잘 들었습니다 :) ',
        description:
          '덕분에 오늘도 수업 잘 들었습니다, 열심히 공부하겠습니다! 감사합니다:)',
        tags: [],
        name: '봄봄',
        createdAt: '6일 전',
        courseTitle: 'HTML+CSS+JS 포트폴리오 실전 퍼블리싱(시즌1)',
        commentCount: 1,
        likeCount: 1,
      },
      {
        id: 19,
        title: '중간에 듣다가 그럼 코끼리다리는 4개인데 이게 주인이 되는건가 ',
        description:
          '이게 맞나? 라고 생각할때 자동차 바퀴 이야기 나와서 개놀랬습니다.궁굼할 법한 것들을 바로바로 긁어주시니까 너무 시원합니다.',
        tags: [],
        name: '범',
        createdAt: '6일 전',
        courseTitle: '자바 ORM 표준 JPA 프로그래밍 - 기본편',
        commentCount: 1,
        likeCount: 0,
      },
      {
        id: 20,
        title: '강의 자료 공유 받고 싶습니다. ',
        description:
          '강의를 수강하고 나니 강의 자료를 받고 싶다는 생각이 들었습니다. 강의 자료를 공유 받을 수 있을까요?',
        tags: [],
        name: 'rudwlsdl77',
        createdAt: '6일 전',
        courseTitle: '고객의 친구가 되기 위한 UX Writing',
        commentCount: 1,
        likeCount: 0,
      },
    ],
  },
}
