export const MentorsDummy = {
  result: [
    {
      id: 1,
      title: '비전공자의 1년만에 네카라쿠배 합격 방법',
      job: '백엔드/서버 개발자',
      career: '주니어 (1~3년)',
      company: '네카라쿠배',
      mentor: '최연찬',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/581610/9946f92b-216b-400c-8c1f-e9029139a871',
      rating: '5.0',
    },
    {
      id: 2,
      title:
        'back-end 신입/주니어 개발자 서비스 회사 취업설계 | 이직 | 기술 면접 상담',
      job: '백엔드/서버 개발자',
      career: '미들 (4~6년)',
      company: '네카라 중 한곳',
      mentor: 'incu',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/117609/09c882a3-a8af-4f14-a19b-9a81256c39d0',
      rating: '5.0',
    },
    {
      id: 3,
      title:
        '신입~주니어 개발자 취직, 이력서&프론트엔드 상담 및 고민, 커리어 및 로드맵 설계',
      job: '프론트엔드/웹퍼블리셔',
      career: '미들 (4~8년)',
      company: '',
      mentor: '장현석',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/36294/c14ef375-cddf-4d75-82d9-055109c79eb6',
      rating: '5.0',
    },
    {
      id: 4,
      title:
        'Spring Framework 기반 백엔드 개발자 입문에 어려움을 겪으시는 분들을 위한 멘토링을 해드릴까 합니다., 커리어 및 로드맵 설계',
      job: '백엔드/서버 개발자',
      career: '시니어 (9년 이상)',
      company: '코드스테이츠',
      mentor: 'Kevin',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/29985/495eda57-0a4e-4c8e-a86d-4edf0ebbafb1',
      rating: '5.0',
    },
    {
      id: 5,
      title: '[3N 출신] 게임 프로그래머 취직, 커리어 고민, 개발 관련 질문',
      job: '게임 클라이언트 개발자',
      career: '미들 (4~8년)',
      company: '',
      mentor: 'KoreaCarrot',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/23830/19d54ce7-8745-4b14-8a73-fe4e2efebd22',
      rating: '5.0',
    },
    {
      id: 6,
      title: '서버 개발자 고민 상담소 👩🏻‍💻',
      job: '백엔드/서버 개발자',
      career: '미들 (4~8년)',
      company: '네카라중 하나',
      mentor: 'Lucy',
      rating: '5.0',
    },
    {
      id: 7,
      title: '비전공자 백엔드 개발자 면접 / 취업',
      job: '백엔드/서버 개발자',
      career: '시니어 (9년 이상)',
      company: '',
      mentor: 'Buzz',
      rating: '',
    },
    {
      id: 8,
      title: 'Python / Django / Web Programming 멘토링',
      job: '백엔드/서버 개발자',
      career: 'Lead 레벨',
      company: '',
      mentor: '김석훈',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/139101/31a12cae-345c-4544-873e-561a76f74007',
      rating: '5.0',
    },
    {
      id: 9,
      title: '개발자 취업, 기술 면접 준비 / 앱개발 방법 / 기술사',
      job: '안드로이드 개발자',
      career: 'Lead 레벨',
      company: '',
      mentor: '기술노트with알렉',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/491366/311487a6-1734-427c-ab8c-5641bf12c403',
      rating: '5.0',
    },
    {
      id: 10,
      title: '비전공자 개발자 / 데이터 / 주니어 커리어 / 면접 / 외국어',
      job: '데이터 엔지니어',
      career: '미들 (4~8년)',
      company: '네카라쿠배',
      mentor: 'Joon',
      rating: '5.0',
    },
    {
      id: 11,
      title: '[대기업 전용] 개발자 자소서 첨삭 및 커리어 상담',
      job: 'SW 엔지니어',
      career: '주니어 (1~3년)',
      company: '삼성전자',
      mentor: 'corleone',
      rating: '',
    },
    {
      id: 12,
      title: 'NLP+AI 분야 커리어 컨설팅 / 논문 함께 읽기',
      job: '데이터 사이언티스트',
      career: 'Lead 레벨',
      company: '네이버',
      mentor: 'Jaewook Kang',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/1044033/d3a5c784-c97b-4879-a97f-6a0fc06ebf13',
      rating: '',
    },
    {
      id: 13,
      title: '백엔드 엔지니어 커리어 이야기 - 초심자 그 너머로',
      job: '백엔드/서버 개발자',
      career: '주니어 (1~3년)',
      company: '카카오페이',
      mentor: 'Heli',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/105536/9cbd6c2b-0989-4deb-9bca-86b4ef3acb88',
      rating: '5.0',
    },
    {
      id: 14,
      title:
        '개발자 신입 취업과 이직 준비 로드맵. 막막함과 고민을 한방에 해결 해드립니다.',
      job: '백엔드/서버 개발자',
      career: '미들 (4~8년)',
      company: '토스',
      mentor: 'So, Relax',
      rating: '5.0',
    },
    {
      id: 15,
      title: '[백엔드] 개발자를 위한 멘토링 & 코드 리뷰',
      job: '백엔드/서버 개발자',
      career: '미들 (4~8년)',
      company: '컬리페이',
      mentor: 'Byung Hyun Choi',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/199520/ed9c8718-ef2a-4ef0-812c-c85627bb2a1b',
      rating: '',
    },
    {
      id: 16,
      title: '백엔드 개발자 실전 모의면접(기술/인성)',
      job: '백엔드/서버 개발자',
      career: '미들 (4~8년)',
      company: '대기업 클라우드 개발자 / 네카라중 한 곳',
      mentor: 'sunny',
      rating: '5.0',
    },
    {
      id: 17,
      title: '코드, 이력서 리뷰 및 취업 상담해 드립니다.',
      job: '',
      career: '',
      company: '',
      mentor: 'Kenu 허광남',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/5525/d32b60e7-3b47-4100-89fa-1d19a1a765d8',
      rating: '5.0',
    },
    {
      id: 18,
      title: '비전공자, 주니어 백엔드 개발자를 위한 상담소',
      job: '백엔드/서버 개발자',
      career: '미들 (4~8년)',
      company: '',
      mentor: '민',
      rating: '5.0',
    },
    {
      id: 19,
      title: '비전공자 개발자 취업 고민 상담 / 알고리즘 공부 방법',
      job: '프론트엔드/웹퍼블리셔',
      career: '주니어 (1~3년)',
      company: '',
      mentor: 'MO',
      rating: '',
    },
    {
      id: 20,
      title: '데이터 사이언스 , 딥러닝 엔지니어, 커리어 및 기술셋 고민',
      job: '머신러닝 엔지니어',
      career: '미들 (4~8년)',
      company: '네카라',
      mentor: 'mskim00135',
      rating: '',
    },
    {
      id: 21,
      title: 'back-end 주니어 개발자 코드 리뷰 |  왜 과제전형에 떨어질까?',
      job: '백엔드/서버 개발자',
      career: '미들 (4~8년)',
      company: '네카라쿠배중 하나',
      mentor: 'incudev',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/960261/b61d7338-97aa-4a7c-8746-7e2d5e0112ee',
      rating: '5.0',
    },
    {
      id: 22,
      title: 'C++ 및 게임 프로그래밍 멘토링',
      job: '',
      career: '',
      company: '',
      mentor: '유틸',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/399202/5df14103-4b5f-4c73-a04b-06bbc86f1085',
      rating: '5.0',
    },
    {
      id: 23,
      title: 'PM & 기획 직무 취준생 멘토링',
      job: '',
      career: '',
      company: '',
      mentor: '원스타',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/507717/8134a658-e8b9-40db-9302-f0bd0e9375fe',
      rating: '5.0',
    },
    {
      id: 24,
      title: '안드로이드 앱 개발 멘토링',
      job: '',
      career: '',
      company: '',
      mentor: '홍드로이드',
      imgUrl:
        'https://cdn.inflearn.com/public/users/thumbnails/321519/1c20bba8-26ca-4aa5-864d-cc14b91d0fbd',
      rating: '',
    },
  ],
}
