export const roadmapsCardDummy = {
  result: [
    {
      imgUrl: 'roadmaps-1.jpeg',
      level: '입문',
      tag1: '#C#',
      tag2: '#Unity',
      title: 'MMORPG 게임 개발, 켠김에 끝판왕까지! (유니티 + C#)',
      instructor: 'Rookiss',
      lectures: '9',
      students: '3147',
    },
    {
      imgUrl: 'roadmaps-2.jpeg',
      level: '입문',
      tag1: '#Python',
      tag2: '#HTML/CSS',
      title:
        '코딩 해볼래요? - 하루 11분, 60일 완성 코딩 왕초보 탈출부터 활용까지!',
      instructor: '인프런',
      lectures: '4',
      students: '2377',
    },
    {
      imgUrl: 'roadmaps-3.jpeg',
      level: '입문',
      tag1: '#Spring',
      tag2: '#MVC',
      title: '우아한형제들 최연소 기술이사 김영한의 스프링 완전 정복',
      instructor: '김영한',
      lectures: '8',
      students: '9999+',
    },
    {
      imgUrl: 'roadmaps-4.jpeg',
      level: '입문',
      tag1: '#Python',
      tag2: '#딥러닝',
      title: '기초부터 응용까지, 한 방에 끝내는 파이썬 (Inflearn Original)',
      instructor: '인프런',
      lectures: '4',
      students: '923',
    },
    {
      imgUrl: 'roadmaps-5.jpeg',
      level: '입문',
      tag1: '#Docker',
      tag2: '#Kubernetes',
      title: '44bits와 함께하는 DevOps 워크숍: 도커부터 쿠버네티스까지!',
      instructor: '너굴',
      lectures: '3',
      students: '300',
    },
    {
      imgUrl: 'roadmaps-6.jpeg',
      level: '입문',
      tag1: '#TypeScript',
      tag2: '#ES6',
      title: '자바스크립트부터 타입스크립트까지 - 타입스크립트 로드맵',
      instructor: '장기효(캡틴판교)',
      lectures: '2',
      students: '631',
    },
    {
      imgUrl: 'roadmaps-7.jpeg',
      level: '입문',
      tag1: '#Python',
      tag2: '#딥러닝',
      title: '프로그래밍 시작하기 - 파이썬 입문부터 인공지능, 머신러닝까지',
      instructor: '인프런',
      lectures: '3',
      students: '666',
    },
    {
      imgUrl: 'roadmaps-8.jpeg',
      level: '초급',
      tag1: '#Java',
      tag2: '#JPA',
      title: '김영한의 스프링 부트와 JPA 실무 완전 정복 로드맵',
      instructor: '김영한',
      lectures: '5',
      students: '6777',
    },
    {
      imgUrl: 'roadmaps-9.jpeg',
      level: '입문',
      tag1: '#Python',
      tag2: '#Pandas',
      title: '뼈문과를 위한 현실 데이터 분석 - 파이썬',
      instructor: '박조은',
      lectures: '7',
      students: '912',
    },
    {
      imgUrl: 'roadmaps-10.jpeg',
      level: '초급',
      tag1: '#함수형 프로그래밍',
      tag2: '#JavaScript',
      title: '인생을 바꾸는 함수형 프로그래밍 👑',
      instructor: '인프런',
      lectures: '3',
      students: '445',
    },
    {
      imgUrl: 'roadmaps-11.jpeg',
      level: '초급',
      tag1: '#프로젝트 관리',
      tag2: '#업무 생산성',
      title: '당신의 협업을 도와줄 효율적인 툴, Jira와 Confluence!',
      instructor: '인프런',
      lectures: '2',
      students: '10',
    },
    {
      imgUrl: 'roadmaps-12.jpeg',
      level: '입문',
      tag1: '#면접',
      tag2: '#포트폴리오',
      title: '비전공자를 위한 개발지식 한 스푼',
      instructor: '인프런',
      lectures: '3',
      students: '181',
    },
    {
      imgUrl: 'roadmaps-13.jpeg',
      level: '초급',
      tag1: '#HTML/CSS',
      tag2: '#jQuery',
      title:
        '중상급 퍼블리싱 실력 Skill Up을 위한 실전 퍼블리싱 포트폴리오 제작 로드맵 (#02)',
      instructor: '코딩웍스(Coding Works)',
      lectures: '7',
      students: '252',
    },
    {
      imgUrl: 'roadmaps-14.jpeg',
      level: '입문',
      tag1: '#Python',
      tag2: '#Pandas',
      title: '주식 퀀트(Quant) 투자로 배워보는 모두를 위한 파이썬(Python)',
      instructor: 'DeepingSauce',
      lectures: '4',
      students: '456',
    },
    {
      imgUrl: 'roadmaps-15.jpeg',
      level: '입문',
      tag1: '#게임개발',
      tag2: '#Unity',
      title: '기획서 작성부터 취업까지 한 번에! - 게임기획 따라하기',
      instructor: 'JamesKim',
      lectures: '4',
      students: '298',
    },
    {
      imgUrl: 'roadmaps-16.jpeg',
      level: '입문',
      tag1: '#C#',
      tag2: '#네트워크',
      title: '게임 서버 프로그래머 로드맵',
      instructor: 'Rookiss',
      lectures: '5',
      students: '432',
    },
    {
      imgUrl: 'roadmaps-17.jpeg',
      level: '초급',
      tag1: '#JavaScript',
      tag2: '#Vue.js',
      title: 'Vue.js의 이해와 프론트엔드 개발 실무 적용',
      instructor: '김정환',
      lectures: '2',
      students: '108',
    },
    {
      imgUrl: 'roadmaps-18.jpeg',
      level: '초급',
      tag1: '#HTML/CSS',
      tag2: '#인터렉티브 웹',
      title: '"Oh!" 감탄사가 나오는 역동적인 인터랙티브 웹사이트를 만들어요.',
      instructor: '1분코딩',
      lectures: '6',
      students: '736',
    },
    {
      imgUrl: 'roadmaps-19.jpeg',
      level: '입문',
      tag1: '#JavaScript',
      tag2: '#함수형 프로그래밍',
      title: '자바스크립트(Javascript) 개념부터 정복까지!',
      instructor: '인프런',
      lectures: '6',
      students: '708',
    },
    {
      imgUrl: 'roadmaps-20.jpeg',
      level: '초급',
      tag1: '#HTML/CSS',
      tag2: '#PHP',
      title: '입문자를 위한 생활코딩 WEB-N PHP 로드맵',
      instructor: '인프런',
      lectures: '5',
      students: '321',
    },
    {
      imgUrl: 'roadmaps-21.jpeg',
      level: '초급',
      tag1: '#Java',
      tag2: '#Spring',
      title: '우아한형제들 백엔드 개발자 취업 로드맵',
      instructor: '인프런',
      lectures: '8',
      students: '2918',
    },
    {
      imgUrl: 'roadmaps-22.jpeg',
      level: '입문',
      tag1: '#JavaScript',
      tag2: '#Vue.js',
      title: '누구나 처음부터 프론트엔드 개발자 로드맵 (Vue.js)',
      instructor: '인프런',
      lectures: '8',
      students: '216',
    },
    {
      imgUrl: 'roadmaps-23.jpeg',
      level: '입문',
      tag1: '#Python',
      tag2: '#Pandas',
      title: '데이터 과학부터 인공지능까지! - DataScience & Al 로드맵',
      instructor: 'TeamLab',
      lectures: '10',
      students: '517',
    },
    {
      imgUrl: 'roadmaps-24.jpeg',
      level: '초급',
      tag1: '#Node.js',
      tag2: '#JavaScript',
      title: 'Javascript 풀스택 로드맵 (+ 트위터 클론앱 만들기 🐦)',
      instructor: '인프런',
      lectures: '5',
      students: '979',
    },
  ],
}
