export const mainPageDummy = {
  result: {
    mainBullets: [
      '클라우드 ☁',
      '프로토타이핑 툴',
      '인프런 동료찾기',
      '2022 추석 위크',
      '이펙티브 자바',
      '신규 강의 🎁',
      '입문 로드맵',
      '인프콘 다시보기',
      'Top 50 👑',
      '지식공유신청',
      '인프런은 🌱',
    ],

    mainBanner: [
      {
        imgUrl: 'main10.png',
        backgroundColor: { backgroundColor: '#3f70f9' },
        spanColor: { color: '#0f121c', backgroundColor: '#9ffffa' },
        textColor: { color: '#ffffff' },
        span: '큐레이션 20%',
        title1: '미래를 위한 투자,',
        title2: '대세는 클라우드 컴퓨팅 ☁️',
        description1: '테크 업계는 지금 클라우드 도입 중! ',
        description2: 'AWS, Azure, GCP 강의를 전부 만나보세요.',
      },
      {
        imgUrl: 'main11.png',
        backgroundColor: { backgroundColor: '#6e7cf8' },
        spanColor: { color: '#000000', backgroundColor: '#ffffff' },
        textColor: { color: '#ffffff' },
        span: '깜짝 할인 20%',
        title1: '기획자와 디자이너라면 주목 👩🏻‍🎨',
        title2: '프로토타이핑 툴 모여라!',
        description1: '동작하는 명확한 이미지로',
        description2: '원하는 걸 효과적으로 전달해요.',
      },
      {
        imgUrl: 'main1.gif',
        backgroundColor: { backgroundColor: '#00c471' },
        spanColor: { color: '#ffffff', backgroundColor: '#00dfff' },
        textColor: { color: '#ffffff' },
        span: '함께해요',
        title1: '함께 성장할',
        title2: '동료를 찾아요 🌿',
        description1: '#우리 #함께성장해요',
        description2: '#동료여어디계신가요?',
      },
      {
        imgUrl: 'main2.png',
        backgroundColor: { backgroundColor: '#ffecbe' },
        spanColor: { color: '#ffffff', backgroundColor: '#008c56' },
        textColor: { color: '#000000' },
        span: '모든 강의 25%',
        title1: '2022 inflearn',
        title2: '풍성한 추석 위크 🌕',
        description1: '매일 성장하는 나를 만드는 시간',
        description2: '',
      },
      {
        imgUrl: 'main9.png',
        backgroundColor: { backgroundColor: '#020204' },
        spanColor: { color: '#ffffff', backgroundColor: '#E50CBE' },
        textColor: { color: '#ffffff' },
        span: '얼리버드 20%',
        title1: '수준 높은 백엔드 개발자가',
        title2: '되고 싶은 당신을 위해',
        description1: '마이크로소프트 개발자 백기선 님과 함께',
        description2: '쉽고 완벽하게 학습하세요.',
      },
      {
        imgUrl: 'main3.gif',
        backgroundColor: { backgroundColor: '#ff7836' },
        spanColor: { backgroundColor: '#007bf8' },
        textColor: {},
        span: '신규 강의',
        title1: '나만 몰랐었던 이 강의~♬',
        title2: '',
        description1: '매일 업데이트 되는',
        description2: '인프런 신규강의를 만나보세요!',
      },
      {
        imgUrl: 'main4.gif',
        backgroundColor: { backgroundColor: '#38e5ff' },
        spanColor: { backgroundColor: '#6344ec' },
        textColor: { color: '#000000' },
        span: '추천 학습 로드맵',
        title1: '왕초보를 위한',
        title2: 'Lv. 1 인프런 로드맵 📖',
        description1: '인프런이 처음이라면, 길라잡이가 되어드릴게요.',
        description2: '',
      },
      {
        imgUrl: 'main5.png',
        backgroundColor: { backgroundColor: '#000000' },
        spanColor: { backgroundColor: '#00b3ff' },
        textColor: {},
        span: '인프콘 다시보기',
        title1: 'INFCON 2022의 뜨거웠던 열기!',
        title2: '온라인에서 다시 만나보세요 🔥',
        description1: '오프닝부터 발표 세션 영상 28개,',
        description2: '토크 콘서트 영상과 클로징까지!',
      },
      {
        imgUrl: 'main6.gif',
        backgroundColor: { backgroundColor: '#D2D9DD' },
        spanColor: { backgroundColor: '#1044ff' },
        textColor: { color: '#000000' },
        span: '오늘 뭐 듣지?',
        title1: '무슨 강의 들을지 고민이라면?',
        title2: '현직자 Top 50 먼저 보기 👀',
        description1: '입문부터 실전까지!',
        description2: '믿고 보는 실무자 Pick',
      },
      {
        imgUrl: 'main7.gif',
        backgroundColor: { backgroundColor: '#086394' },
        spanColor: { backgroundColor: '#00de84', color: '#002235' },
        textColor: {},
        span: '지식공유신청',
        title1: '나누는 지식만큼',
        title2: '커지는 보람과 보상',
        description1: '인프런 지식공유자로',
        description2: '높은 수익과 가치를 만들어 보세요.',
      },
      {
        imgUrl: 'main8.png',
        backgroundColor: { backgroundColor: '#59cf92' },
        spanColor: { backgroundColor: '#ffffff', color: '#59cf92' },
        textColor: {},
        span: '인프런 소개',
        title1: '우리는 성장기회의',
        title2: '평등을 추구합니다.',
        description1: '누구나 배움의 기회를 누리고 꿈을 이룰 수 있도록!',
        description2: '인프런과 함께 배우고, 나누고, 성장하세요.',
      },
    ],

    freeCourse: [
      {
        imgUrl: 'free-course-9.jpeg',
        lectureTitle:
          '스프링 입문 - 코드로 배우는 스프링 부트, 웹 MVC, DB 접근 기술',
        instructor: '김영한',
        badge: '',
        badgeDay: '',
        starCnt: 5,
        reviewCnt: 4265,
        del: '',
        price: '무료',
        students: '53500',
        isNew: false,
        isUpdate: true,
        isDiscount: false,
        level: '초급',
        category: '백엔드, 웹 개발',
        skill: 'Java, Spring, MVC',
      },
      {
        imgUrl: 'free-course-10.jpeg',
        lectureTitle: '인프콘 2022 다시보기',
        instructor: '인프런',
        badge: '',
        badgeDay: '',
        starCnt: 5,
        reviewCnt: 8,
        del: '',
        price: '무료',
        students: '11800',
        isNew: false,
        isUpdate: true,
        isDiscount: false,
        level: '입문',
        category: '교양 · 기타, 기타',
        skill: '',
      },
      {
        imgUrl: 'free-course-6.jpeg',
        lectureTitle: '따라하면서 배우는 고박사의 유니티 기초',
        instructor: '고박사',
        starCnt: 5,
        reviewCnt: 85,
        price: '무료',
        students: '6500',
        isNew: false,
        level: '입문',
        category: '게임 프로그래밍, 게임 개발',
        skill: 'Unity',
      },
      {
        imgUrl: 'free-course-7.jpeg',
        lectureTitle: '컴퓨터,웹,코딩,프로그래밍의 시작 - Web1',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 508,
        price: '무료',
        students: '12500',
        isNew: false,
        level: '입문',
        category: '웹 개발',
        skill: 'HTML/CSS',
      },
      {
        imgUrl: 'free-course-8.jpeg',
        lectureTitle: '30분 요약강좌 시즌5 : 알작딱깔센 flex & grid',
        instructor: '제주코딩베이스캠프',
        starCnt: 5,
        reviewCnt: 7,
        price: '무료',
        students: '300',
        isNew: true,
        level: '초급',
        category: '웹 개발, 프론트엔드, 웹 퍼블리싱',
        skill: 'HTML/CSS, 반응형 웹, Flex',
      },
      {
        imgUrl: 'free-course-5.jpeg',
        lectureTitle: '클라우드 서비스 AWS',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 174,
        price: '무료',
        students: '6100',
        isNew: false,
        level: '초급',
        category: '데브옵스 · 인프라, 클라우드',
        skill: 'AWS',
      },

      {
        imgUrl: 'free-course-2.jpeg',
        lectureTitle:
          '[백문이불여일타] 데이터 분석을 위한 SQL 실전표 (무료 미니 코스)',
        instructor: '데이터라인',
        starCnt: 5,
        reviewCnt: 32,
        price: '무료',
        students: '3100',
        isNew: false,
        level: '중급이상',
        category: '데이터 분석, 기타',
        skill: 'SQL',
      },
      {
        imgUrl: 'free-course-3.jpeg',
        lectureTitle: '[코드팩토리] [입문] Dart 언어 4시간만에 완전정복',
        instructor: '코드팩토리',
        starCnt: 4,
        reviewCnt: 108,
        price: '무료',
        students: '1600',
        isNew: false,
        level: '입문',
        category: '프로그래밍 언어, 모바일 앱 개발',
        skill: 'Flutter, 객체지향, 함수형 프로그래밍',
      },
      {
        imgUrl: 'free-course-1.jpeg',
        lectureTitle: '웹 게임을 만들며 배우는 React',
        instructor: '조현영',
        starCnt: 4,
        reviewCnt: 237,
        price: '무료',
        students: '8700',
        isNew: false,
        level: '초급',
        category: '프론트엔드, 웹 개발',
        skill: 'React',
      },
      {
        imgUrl: 'free-course-4.jpeg',
        lectureTitle: '생활코딩 - SQLite',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 3,
        price: '무료',
        students: '100',
        isNew: false,
        level: '초급',
        category: '데이터베이스',
        skill: 'DBMS/RDBMS, SQLite',
      },
      {
        imgUrl: 'free-course-11.jpeg',
        lectureTitle: '생활코딩 - 자바스크립트 (JavaScript) 기본',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 372,
        price: '무료',
        students: '20300',
        isNew: false,
        level: '입문',
        category: '프로그래밍 언어',
        skill: 'JavaScript',
      },
      {
        imgUrl: 'free-course-12.jpeg',
        lectureTitle: 'JPA & Spring Data JPA 기초',
        instructor: '최범균',
        starCnt: 5,
        reviewCnt: 104,
        price: '무료',
        students: '500',
        isNew: true,
        level: '초급',
        category: '백엔드, 웹 개발',
        skill: 'Spring, JPA',
      },
    ],
    newbieCourse: [
      {
        imgUrl: 'newbie-course-6.jpeg',
        lectureTitle: '비전공자를 위한 개발자 취업 올인원 가이드 [통합편]',
        badge: '25',
        badgeDay: '2',
        instructor: '한정수',
        starCnt: 5,
        reviewCnt: 126,
        del: '₩77,000',
        price: '₩57,750',
        students: '2400',
        isNew: false,
        isUpdate: false,
        isDiscount: true,
        level: '입문',
        category: '취업 · 이직, 교양 · 기타',
        skill: '면접, 포트폴리오',
      },
      {
        imgUrl: 'newbie-course-2.jpeg',
        lectureTitle:
          '실제 이력서 사례로 알아보는 [합격하는 이력서] 작성 가이드',
        instructor: '워니',
        starCnt: 5,
        reviewCnt: 116,
        price: '₩49,500',
        students: '600',
        isNew: false,
        level: '입문',
        category: '취업 · 이직, 교양 · 기타',
        skill: '이력서, 면접',
      },
      {
        imgUrl: 'newbie-course-3.jpeg',
        lectureTitle: '프로그래밍 시작하기:파이썬 입문(Inflearn Original)',
        badge: '25',
        instructor: '인프런',
        starCnt: 5,
        reviewCnt: 687,
        del: '₩55,000',
        price: '₩41,250',
        students: '13100',
        isNew: false,
        isUpdate: true,
        level: '입문',
        category: '프로그래밍 언어',
        skill: 'Python, 딥러닝',
      },
      {
        imgUrl: 'newbie-course-4.jpeg',
        lectureTitle:
          '[C#과 유니티로 만드는 MMORPG 게임 개발 시리즈] Part1: C# 기초: 프로그래밍 입문',
        instructor: 'Rookiss',
        badge: '25',
        badgeDay: '2',
        starCnt: 5,
        reviewCnt: 50,
        del: '₩44,000',
        price: '₩33,000',
        students: '100',
        isNew: false,
        isUpdate: true,
        isDiscount: true,
        level: '입문',
        category: '게임 개발, 프로그래밍 언어',
        skill: 'C#',
      },

      {
        imgUrl: 'newbie-course-8.jpeg',
        lectureTitle: '비전공자를 위한 진짜 입문 올인원 개발 클래스',
        instructor: '그랩',
        badge: '25',
        badgeDay: '2',
        starCnt: 5,
        reviewCnt: 116,
        del: '₩143,000',
        price: '₩107,250',
        students: '2100',
        isNew: false,
        isUpdate: true,
        isDiscount: true,
        level: '입문',
        category: '풀스택, 웹 개발, 취업 · 이직, 프론트엔드',
        skill: 'JavaScript, React, Node.js',
      },

      {
        imgUrl: 'newbie-course-5.jpeg',
        lectureTitle: 'Flutter 앱 개발 완성',
        instructor: 'DevStory',
        starCnt: 4,
        reviewCnt: 18,
        delPrice: '',
        price: '₩64,900',
        students: '200',
        isNew: false,
        level: '입문',
        category: '모바일 앱 개발',
        skill: 'Flutter',
      },

      {
        imgUrl: 'newbie-course-7.jpeg',
        lectureTitle: '블렌더 처음 시작부터 로우폴리 3D 애니메이션 까지',
        instructor: 'AZTechnology',
        badge: '25',
        badgeDay: '2',
        starCnt: 5,
        reviewCnt: 5,
        del: '₩49,500',
        price: '₩37,120',
        students: '100',
        isNew: false,
        isUpdate: false,
        isDiscount: true,
        level: '입문',
        category: 'CAD · 3D 모델링, 디자인 툴, 게임 아트 · 그래픽',
        skill: 'Blender',
      },

      {
        imgUrl: 'newbie-course-1.jpeg',
        lectureTitle: '입문자를 위한 게임 프로그래머 개론',
        instructor: 'Rookiss',
        starCnt: 4,
        reviewCnt: 8,
        price: '₩11,000',
        students: '700',
        isNew: false,
        level: '입문',
        category: '기타, 게임개발, 기타',
        skill: '',
      },
    ],
    roadMapCourse: [
      {
        imgUrl: 'roadmap-course-5.jpeg',
        title: '우아한형제들 최연소 기술이사 김영한의 스프링 완전 정복',
      },
      {
        imgUrl: 'roadmap-course-6.jpeg',
        title: '뼈문과를 위한 현실 데이터 분석 - 파이썬',
      },
      {
        imgUrl: 'roadmap-course-7.jpeg',
        title: '자바스크립트부터 타입스크립트까지 - 타입스크립트 로드맵',
      },
      {
        imgUrl: 'roadmap-course-8.jpeg',
        title: '비전공자를 위한 개발지식 한 스푼',
      },
      {
        imgUrl: 'roadmap-course-9.jpeg',
        title: '인생을 바꾸는 함수형 프로그래밍 👑',
      },
      {
        imgUrl: 'roadmap-course-1.jpeg',
        title: '코딩 해볼래요? - 하루 11분, 60일 완성 코딩 왕초보 탈출부터',
      },
      {
        imgUrl: 'roadmap-course-2.jpeg',
        title: '코딩테스트 최적화 로드맵 🕵',
      },
      {
        imgUrl: 'roadmap-course-3.jpeg',
        title: '자바 개발자 Level Up! - 더 나은 자바 개발자 되기',
      },
      {
        imgUrl: 'roadmap-course-4.jpeg',
        title: '프로그래밍 시작하기 - 파이썬 입문부터 인공지능, 머신러닝까지',
      },
    ],
    curationCourse: [
      {
        imgUrl: 'curation-course-1.jpeg',
        title: '리포트부터 발표자 소감까지, 인프콘 2022 하이라이트',
        description:
          '인프런의 첫 오프라인 IT 콘퍼런스, 인프콘 2022! 어떤 사람들과 함께했고, 어떤 이야기가 오갔을까요? “Learn, Share & Grow” 함께 배우고 나누고 성장하세요.',
      },
      {
        imgUrl: 'curation-course-2.jpeg',
        title: '(💚특별 연장) 2022 인프런 추석 위크',
        description:
          '안녕하세요. 인프런입니다.밝은 보름달이 기다려지는 추석이 성큼 다가왔어요!온 가족이 모이는 명절인 만큼인프런도 다 같이 모여 상반기를 돌아봤습니다.🌕인프러너와 유튜브 라이브 방송에서 만나실시간으로 이야기도 하고주석 코드를 이용한 재미있는 이벤트도 함께 하고무려 1,300여명의 인프러너와 함께한 인프콘도 있었죠.',
      },
      {
        imgUrl: 'curation-course-3.jpeg',
        title: '[큐레이션] INFCON 2022 기념 릴레이 할인 통합편!',
        description:
          '🌱 🏃 🎫 인프런의 첫 번째 오프라인 콘퍼런스,INFCON 2022! 인프콘 발표자분들 중엔인프런 지식공유자가 많다는 사실, 아시나요?오늘은 인프콘을 기다리는 여러분들께몇몇 지식공유자를 소개해드리려고 찾아왔어요.',
      },
    ],
    recentCourse: [
      {
        imgUrl: 'recent-course-8.jpeg',
        lectureTitle: 'UI와 함께 배우는 Swift - 레벨 2',
        badge: '',
        badgeDay: '',
        instructor: '리이오',
        starCnt: 0,
        reviewCnt: 0,
        del: '',
        price: '무료',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: false,
        level: '입문',
        category: '모바일 앱 개발, 프로그래밍 언어',
        skill: 'Swift, SwiftUI',
      },
      {
        imgUrl: 'recent-course-7.jpeg',
        lectureTitle: '[입문자를 위한 UE5] Part2.언리얼 엔진 2D 게임 개발 입문',
        badge: '30',
        badgeDay: '',
        instructor: 'Rookiss',
        starCnt: 0,
        reviewCnt: 0,
        del: '₩55,000',
        price: '₩38,500',
        students: '100',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        level: '초급',
        category: '게임 프로그래밍, 게임 개발',
        skill: 'Unreal Engine, UE Blueprint',
      },
      {
        imgUrl: 'recent-course-6.jpeg',
        lectureTitle: '계산기로 시작해보는 SwiftUI',
        badge: '',
        badgeDay: '',
        instructor: '리이오',
        starCnt: 0,
        reviewCnt: 0,
        del: '',
        price: '무료',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: false,
        level: '초급',
        category: '모바일 앱 개발',
        skill: 'SwiftUI, Swift',
      },
      {
        imgUrl: 'recent-course-5.jpeg',
        lectureTitle: '엑셀 분석작업의 모든것',
        badge: '10',
        badgeDay: '',
        instructor: '은희쌤',
        starCnt: 0,
        reviewCnt: 0,
        del: '₩11,000',
        price: '₩9,900',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        level: '초급',
        category: '오피스',
        skill: 'Excel, MS-Office',
      },
      {
        imgUrl: 'recent-course-4.jpeg',
        lectureTitle:
          '따라하며 배우는 노드, 리액트 시리즈 - 레딧 사이트 만들기(NextJS)',
        badge: '20',
        badgeDay: '',
        instructor: 'John Ahn',
        starCnt: 0,
        reviewCnt: 0,
        del: '₩44,000',
        price: '₩35,200',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        level: '초급',
        category: '클론코딩, Node.js, React',
        skill: '카피라이팅, 서비스 기획',
      },
      {
        imgUrl: 'recent-course-3.jpeg',
        lectureTitle: '퍼블리셔 개인 포트폴리오 홈페이지 제작 완벽 가이드(PDF)',
        badge: '20',
        badgeDay: '',
        instructor: '코딩웍스(Coding Works)',
        starCnt: 0,
        reviewCnt: 0,
        del: '₩38,500',
        price: '₩30,800',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        level: '초급',
        category: '웹 퍼블리싱, 취업 · 이직',
        skill: '포트폴리오, 웹 디자인, HTML/CSS',
      },
      {
        imgUrl: 'recent-course-2.jpeg',
        lectureTitle: '모두의 깃 & 깃허브',
        badge: '30',
        badgeDay: '',
        instructor: '강민철',
        starCnt: 0,
        reviewCnt: 0,
        del: '₩24,200',
        price: '₩16,940',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        level: '입문',
        category: '개발도구',
        skill: 'Github, Git',
      },
      {
        imgUrl: 'recent-course-1.jpeg',
        lectureTitle: "고객의 친구가 되기 위한 	'UX Writing'",
        badge: '24',
        badgeDay: '',
        instructor: '켈리폴리',
        starCnt: 0,
        reviewCnt: 0,
        del: '₩44,000',
        price: '₩30,800',
        students: '',
        isNew: true,
        isUpdate: false,
        isDiscount: true,
        level: '입문',
        category: 'UX/UI, 기획 · 전략 · PM',
        skill: '카피라이팅, 서비스 기획',
      },
    ],
    banner2: [
      {
        imgUrl:
          'https://cdn.inflearn.com/public/main_sliders/3b67a1a1-aae3-442e-8e17-791b7cdfb5f5/bottom-1920-205-%281111%29.jpg',
        title1: '모든 팀원이 인프런의 강의들을',
        title2: '자유롭게 학습하는 환경을 제공해주세요.',
        subtext: '비즈니스 알아보기',
      },
      {
        imgUrl:
          'https://cdn.inflearn.com/public/main_sliders/38744ba0-b12a-491a-9ca2-43375c3905ba/share-you.jpg',
        title1: '지식을 나눠주세요. ',
        title2: '쉽게 시작하고 합당한 보상을 받을 수 있어요.',
        subtext: '지식공유 알아보기',
      },
      {
        imgUrl:
          'https://cdn.inflearn.com/public/main_sliders/39bcb91f-64a4-4a16-8878-e8dc7cd342e8/bottom-1920-205-%28221%29.jpg',
        fontColor: '#ffffff',
        title1: '당신은 더 좋은 곳에 갈 수 있어요.',
        title2: '지금 열려있는 채용공고를 확인해보세요.',
        subtext: '공고 확인하기',
      },
    ],
  },
}
