export const mainPageDummy = {
  result: {
    mainBanner: [
      {
        imgUrl: 'main1.gif',
        backgroundColor: { backgroundColor: '#00c471' },
        spanColor: { color: '#ffffff', backgroundColor: '#00dfff' },
        textColor: { color: '#ffffff' },
        span: '함께해요',
        title1: '함께 성장할',
        title2: '동료를 찾아요 🌿',
        description1: '#우리 #함께성장해요',
        description2: '#동료여어디계신가요?',
        bullet: '인프런 동료찾기',
      },
      {
        imgUrl: 'main2.png',
        backgroundColor: { backgroundColor: '#ffecbe' },
        spanColor: { color: '#ffffff', backgroundColor: '#008c56' },
        textColor: { color: '#000000' },
        span: '모든 강의 25%',
        title1: '2022 inflearn',
        title2: '풍성한 추석 위크 🌕',
        description1: '매일 성장하는 나를 만드는 시간',
        description2: '',
        bullet: '2022 추석 위크',
      },
      {
        imgUrl: 'main3.gif',
        backgroundColor: { backgroundColor: '#ff7836' },
        spanColor: { backgroundColor: '#007bf8' },
        textColor: {},
        span: '신규 강의',
        title1: '나만 몰랐었던 이 강의~♬',
        title2: '',
        description1: '매일 업데이트 되는',
        description2: '인프런 신규강의를 만나보세요!',
        bullet: '신규 강의 🎁',
      },
      {
        imgUrl: 'main4.gif',
        backgroundColor: { backgroundColor: '#38e5ff' },
        spanColor: { backgroundColor: '#6344ec' },
        textColor: { color: '#000000' },
        span: '추천 학습 로드맵',
        title1: '왕초보를 위한',
        title2: 'Lv. 1 인프런 로드맵 📖',
        description1: '인프런이 처음이라면, 길라잡이가 되어드릴게요.',
        description2: '',
        bullet: '입문 로드맵',
      },
      {
        imgUrl: 'main5.png',
        backgroundColor: { backgroundColor: '#000000' },
        spanColor: { backgroundColor: '#00b3ff' },
        textColor: {},
        span: '인프콘 다시보기',
        title1: 'INFCON 2022의 뜨거웠던 열기!',
        title2: '온라인에서 다시 만나보세요 🔥',
        description1: '오프닝부터 발표 세션 영상 28개,',
        description2: '토크 콘서트 영상과 클로징까지!',
        bullet: '인프콘 다시보기',
      },
      {
        imgUrl: 'main6.gif',
        backgroundColor: { backgroundColor: '#D2D9DD' },
        spanColor: { backgroundColor: '#1044ff' },
        textColor: { color: '#000000' },
        span: '오늘 뭐 듣지?',
        title1: '무슨 강의 들을지 고민이라면?',
        title2: '현직자 Top 50 먼저 보기 👀',
        description1: '입문부터 실전까지!',
        description2: '믿고 보는 실무자 Pick',
        bullet: 'Top 50 👑',
      },
      {
        imgUrl: 'main7.gif',
        backgroundColor: { backgroundColor: '#086394' },
        spanColor: { backgroundColor: '#00de84', color: '#002235' },
        textColor: {},
        span: '지식공유신청',
        title1: '나누는 지식만큼',
        title2: '커지는 보람과 보상',
        description1: '인프런 지식공유자로',
        description2: '높은 수익과 가치를 만들어 보세요.',
        bullet: '지식공유신청',
      },
      {
        imgUrl: 'main8.png',
        backgroundColor: { backgroundColor: '#59cf92' },
        spanColor: { backgroundColor: '#ffffff', color: '#59cf92' },
        textColor: {},
        span: '인프런 소개',
        title1: '우리는 성장기회의',
        title2: '평등을 추구합니다.',
        description1: '누구나 배움의 기회를 누리고 꿈을 이룰 수 있도록!',
        description2: '인프런과 함께 배우고, 나누고, 성장하세요.',
        bullet: '인프런은 🌱',
      },
    ],

    freeCourse: [
      {
        imgUrl: 'free-course-1.jpeg',
        lectureTitle: '웹 게임을 만들며 배우는 React',
        instructor: '조현영',
        starCnt: 4,
        reviewCnt: 237,
        price: '무료',
        students: '8700',
        isNew: true, //새강의 tag
        level: '초급',
        category: '프론트엔드, 웹 개발',
        skill: 'React',
      },
      {
        imgUrl: 'free-course-2.jpeg',
        lectureTitle:
          '[백문이불여일타] 데이터 분석을 위한 SQL 실전표 (무료 미니 코스)',
        instructor: '데이터라인',
        starCnt: 5,
        reviewCnt: 32,
        price: '무료',
        students: '3100',
        isNew: false, //새강의 tag
        level: '중급이상',
        category: '데이터 분석, 기타',
        skill: 'SQL',
      },
      {
        imgUrl: 'free-course-3.jpeg',
        lectureTitle: '[코드팩토리] [입문] Dart 언어 4시간만에 완전정복',
        instructor: '코드팩토리',
        starCnt: 4,
        reviewCnt: 108,
        price: '무료',
        students: '1600',
        isNew: false, //새강의 tag
        level: '입문',
        category: '프로그래밍 언어, 모바일 앱 개발',
        skill: 'Flutter, 객체지향, 함수형 프로그래밍',
      },
      {
        imgUrl: 'free-course-4.jpeg',
        lectureTitle: '생활코딩 - SQLite',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 3,
        price: '무료',
        students: '100',
        isNew: true, //새강의 tag
        level: '초급',
        category: '데이터베이스',
        skill: 'DBMS/RDBMS, SQLite',
      },
      {
        imgUrl: 'free-course-5.jpeg',
        lectureTitle: '클라우드 서비스 AWS',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 174,
        price: '무료',
        students: '6100',
        isNew: false, //새강의 tag
        level: '초급',
        category: '데브옵스 · 인프라, 클라우드',
        skill: 'AWS',
      },
      {
        imgUrl: 'free-course-6.jpeg',
        lectureTitle: '따라하면서 배우는 고박사의 유니티 기초',
        instructor: '고박사',
        starCnt: 5,
        reviewCnt: 85,
        price: '무료',
        students: '6500',
        isNew: false, //새강의 tag
        level: '입문',
        category: '게임 프로그래밍, 게임 개발',
        skill: 'Unity',
      },
      {
        imgUrl: 'free-course-7.jpeg',
        lectureTitle: '컴퓨터,웹,코딩,프로그래밍의 시작 - Web1',
        instructor: 'Egoing Lee',
        starCnt: 5,
        reviewCnt: 508,
        price: '무료',
        students: '12500',
        isNew: false, //새강의 tag
        level: '입문',
        category: '웹 개발',
        skill: 'HTML/CSS',
      },
      {
        imgUrl: 'free-course-8.jpeg',
        lectureTitle: '30분 요약강좌 시즌5 : 알작딱깔센 flex & grid',
        instructor: '제주코딩베이스캠프',
        starCnt: 5,
        reviewCnt: 7,
        price: '무료',
        students: '300',
        isNew: false, //새강의 tag
        level: '초급',
        category: '웹 개발, 프론트엔드, 웹 퍼블리싱',
        skill: 'HTML/CSS, 반응형 웹, Flex',
      },
    ],
  },
}
